version: "3"


services:
 elasticsearch: 
  build: elasticsearch/
  container_name: elastic
  ports:
   - 9200:9200
   - 9300:9300
  network_mode: host
  restart: always
 one-shot:
  build: python_create_index/
  container_name: one-shot
  environment:
   - HOST=$HOST
   - PORT=$PORT
  depends_on:
    - elasticsearch
  network_mode: host
